### ISSUE TITLE
Bot outputs error on attempt to use .listParameter

### ISSUE THREAD

**Issue by SSwiftGamer440** [SSwiftGamer440/HackersPy#4]
same as title
Also log outputs this
Ignoring exception in command listParameter:
Traceback (most recent call last):
  File "C:\Users\1154789\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\1154789\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 721, in invoke
    await self.prepare(ctx)
  File "C:\Users\1154789\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 685, in prepare
    await self._parse_arguments(ctx)
  File "C:\Users\1154789\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 608, in _parse_arguments
    kwargs[name] = await self.transform(ctx, param)
  File "C:\Users\1154789\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 445, in transform
    raise MissingRequiredArgument(param)
discord.ext.commands.errors.MissingRequiredArgument: args is a required argument that is missing.

**Comment by molchu** [comment]
Please see #general in discord
